export const AGENTS = [
  {
    id: 'agt-ow-001',
    name: 'ASA Creation Agent',
    version: '1.2.0',
    owner: 'ITSOE / Operations Workspace Platform Team',
    description: 'End-to-end agent for initiating and structuring Advisory Services & Analytics (ASA) activities in the Operations Workspace. Handles CPF alignment checks, portfolio overlap scans, concept note generation, Dataverse record population, and SharePoint document upload.',
    status: 'active',
    approval_status: 'Approved',
    data_classification: 'Official Use Only',
    allowed_user_roles: ['TTL', 'Practice Manager', 'Sector Specialist', 'Portfolio Officer'],
    skills: [
      'ASA lifecycle management',
      'CPF alignment analysis',
      'Portfolio overlap detection',
      'Concept Note generation',
      'Dataverse record creation',
      'SharePoint document upload',
      'RAS governance compliance',
      'Multi-intent NL parsing',
    ],
    supported_intents: [
      'initiate_asa',
      'check_cpf_alignment',
      'scan_portfolio_overlap',
      'generate_concept_note',
      'populate_dataverse_record',
      'upload_to_sharepoint',
      'flag_alignment_gaps',
      'retrieve_prior_wbg_work',
    ],
    input_schema: {
      type: 'object',
      required: ['asa_title', 'country', 'global_practice', 'asa_type'],
      properties: {
        asa_title:        { type: 'string', description: 'Full ASA title as it will appear in the Operations Workspace' },
        country:          { type: 'string', description: 'Target country (ISO3 or full name)' },
        global_practice:  { type: 'string', enum: ['MTI', 'FCI', 'HNP', 'SURR', 'SPJ', 'INFRA', 'ENV', 'AGR', 'DIG', 'GOV'], description: 'World Bank Global Practice code' },
        asa_type:         { type: 'string', enum: ['RAS', 'ESW', 'TA', 'NLTA'], description: 'ASA instrument type' },
        budget_usd:       { type: 'number', description: 'Estimated budget in USD' },
        delivery_months:  { type: 'integer', description: 'Planned delivery timeline in months' },
        topic_codes:      { type: 'array', items: { type: 'string' }, description: 'WBG topic codes (e.g. CC, FP, PDM)' },
        output_types:     { type: 'array', items: { type: 'string', enum: ['Policy Note', 'Technical Paper', 'Report', 'Workshop'] } },
        client:           { type: 'string', description: 'Client ministry or organization name' },
        free_text_prompt: { type: 'string', description: 'Natural language instruction from the TTL' },
      },
    },
    output_schema: {
      type: 'object',
      properties: {
        asa_record_id:      { type: 'string', description: 'Dataverse-assigned ASA record ID' },
        concept_note_draft: { type: 'string', description: 'Structured ASA Concept Note in markdown' },
        cpf_alignment:      { type: 'object', properties: { pillars: { type: 'array', items: { type: 'string' } }, gaps: { type: 'array', items: { type: 'string' } } } },
        portfolio_overlap:  { type: 'array', items: { type: 'object', properties: { asa_id: { type: 'string' }, title: { type: 'string' }, overlap_type: { type: 'string' } } } },
        sharepoint_url:     { type: 'string', description: 'SharePoint document library URL of uploaded Concept Note' },
        hitl_summary:       { type: 'object', description: 'Structured review package for TTL HITL gate' },
        alignment_flags:    { type: 'array', items: { type: 'string' }, description: 'Risk and alignment issues flagged for TTL review' },
      },
    },
    runtime_config: {
      model: 'gpt-4o',
      temperature: 0.2,
      max_tokens: 8192,
      top_p: 0.95,
      frequency_penalty: 0.1,
    },
    tools_used: ['Knowledge Engine API', 'Dataverse Connector', 'SharePoint Connector', 'Azure SQL Connector'],
    memory_settings: {
      type: 'vector_store',
      window_size: 20,
      summarize_after: 40,
      store_embeddings: true,
    },
    timeout_seconds: 300,
    system_prompt: 'You are the ASA Creation Agent for the World Bank Operations Workspace. Given a TTL natural language instruction, you parse multi-intent requests, retrieve CPF and portfolio context from the Knowledge Engine, generate a structured ASA Concept Note, populate the Dataverse OW record, and upload documentation to SharePoint. All tool calls are mediated through the Tool Registry. You must surface alignment gaps and risks to the TTL at the HITL gate before any record is promoted to Submitted status.',
    audit_log: [
      { event: 'created',  actor: 'admin@worldbank.org',          timestamp: '2025-01-10T09:00:00Z', delta: { version: '1.0.0', status: 'active', approval_status: 'Pending' } },
      { event: 'updated',  actor: 'ow-platform@worldbank.org',    timestamp: '2025-03-05T14:30:00Z', delta: { version: '1.1.0', tools_used: '+SharePoint Connector, +Azure SQL Connector' } },
      { event: 'approved', actor: 'governance@worldbank.org',     timestamp: '2025-03-20T11:00:00Z', delta: { approval_status: 'Pending → Approved' } },
      { event: 'updated',  actor: 'ow-platform@worldbank.org',    timestamp: '2025-05-01T08:00:00Z', delta: { version: '1.2.0', runtime_config: 'max_tokens 4096 → 8192' } },
    ],
  },
  {
    id: 'agt-ow-002',
    name: 'Portfolio Analytics Agent',
    version: '2.1.0',
    owner: 'Development Economics Vice Presidency (DEC)',
    description: 'Analyzes the active OW project and ASA portfolio for a given country, Global Practice, or theme. Detects overlap, duplication risk, and strategic gaps. Queries Dataverse and Azure SQL for live financial and pipeline data.',
    status: 'active',
    approval_status: 'Approved',
    data_classification: 'Official Use Only',
    allowed_user_roles: ['TTL', 'Economist', 'Portfolio Officer', 'Practice Manager', 'VP'],
    skills: [
      'Portfolio overlap detection',
      'Duplication risk assessment',
      'Financial summary aggregation',
      'Pipeline gap analysis',
      'Disbursement trend analysis',
      'Country partnership framework mapping',
    ],
    supported_intents: [
      'scan_portfolio',
      'detect_overlap',
      'retrieve_financial_summary',
      'map_cpf_alignment',
      'identify_pipeline_gaps',
      'compare_country_portfolios',
    ],
    input_schema: {
      type: 'object',
      required: ['country'],
      properties: {
        country:         { type: 'string', description: 'Target country ISO3 or name' },
        global_practice: { type: 'string', description: 'Filter by Global Practice code' },
        topic_codes:     { type: 'array', items: { type: 'string' }, description: 'WBG topic codes to filter' },
        status_filter:   { type: 'array', items: { type: 'string', enum: ['Active', 'Pipeline', 'Closed'] } },
        fiscal_year:     { type: 'integer', description: 'WBG fiscal year for financial data' },
      },
    },
    output_schema: {
      type: 'object',
      properties: {
        portfolio_items:   { type: 'array', items: { type: 'object', properties: { asa_id: { type: 'string' }, title: { type: 'string' }, status: { type: 'string' }, budget: { type: 'number' }, ttl: { type: 'string' } } } },
        overlap_risks:     { type: 'array', items: { type: 'string' } },
        financial_summary: { type: 'object', properties: { total_committed: { type: 'number' }, disbursed: { type: 'number' }, closing_fy: { type: 'integer' } } },
        gaps_identified:   { type: 'array', items: { type: 'string' } },
      },
    },
    runtime_config: {
      model: 'gpt-4o',
      temperature: 0.1,
      max_tokens: 4096,
      top_p: 0.95,
      frequency_penalty: 0.0,
    },
    tools_used: ['Dataverse Connector', 'Azure SQL Connector'],
    memory_settings: {
      type: 'sliding_window',
      window_size: 10,
      summarize_after: 20,
      store_embeddings: false,
    },
    timeout_seconds: 120,
    system_prompt: 'You are the Portfolio Analytics Agent. You query live Dataverse and Azure SQL data to surface overlap, duplication risk, and strategic gaps in the OW portfolio for a given country and Global Practice.',
    audit_log: [
      { event: 'created',  actor: 'admin@worldbank.org',       timestamp: '2024-11-01T10:00:00Z', delta: { version: '1.0.0', status: 'active', approval_status: 'Pending' } },
      { event: 'approved', actor: 'governance@worldbank.org',  timestamp: '2024-11-20T09:00:00Z', delta: { approval_status: 'Pending → Approved' } },
      { event: 'updated',  actor: 'dec-team@worldbank.org',    timestamp: '2025-02-10T15:00:00Z', delta: { version: '2.1.0', skills: '+Disbursement trend analysis' } },
    ],
  },
  {
    id: 'agt-ow-003',
    name: 'Knowledge Retrieval Agent',
    version: '1.5.0',
    owner: 'ITSOE / Knowledge Management Unit',
    description: 'Retrieves authoritative WBG knowledge using hybrid semantic + keyword search against the Azure AI Search index. Covers CPF documents, policy notes, ESW reports, ICRs, and global good practice literature stored in SharePoint Online and Documentum.',
    status: 'active',
    approval_status: 'Approved',
    data_classification: 'Official Use Only',
    allowed_user_roles: ['TTL', 'Economist', 'Policy Analyst', 'Research Analyst', 'Sector Specialist'],
    skills: [
      'Hybrid semantic + BM25 search',
      'Cross-encoder reranking',
      'Document-level access control',
      'CPF pillar extraction',
      'Source citation generation',
      'Multi-query retrieval',
    ],
    supported_intents: [
      'retrieve_cpf_context',
      'find_prior_analytical_work',
      'search_policy_documents',
      'retrieve_good_practice_references',
      'extract_cpf_pillars',
      'search_by_topic_code',
    ],
    input_schema: {
      type: 'object',
      required: ['query'],
      properties: {
        query:           { type: 'string', description: 'Natural language search query' },
        country:         { type: 'string', description: 'Filter results by country' },
        doc_types:       { type: 'array', items: { type: 'string', enum: ['CPF', 'Policy Note', 'ESW', 'ICR', 'Working Paper', 'Report'] } },
        top_k:           { type: 'integer', default: 10, description: 'Number of chunks to retrieve' },
        rerank:          { type: 'boolean', default: true, description: 'Apply cross-encoder reranking' },
        access_level:    { type: 'string', enum: ['public', 'official', 'confidential'], description: 'Caller access level for document-level ACL enforcement' },
      },
    },
    output_schema: {
      type: 'object',
      properties: {
        chunks: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              chunk_id:    { type: 'string' },
              document:    { type: 'string', description: 'Source document title' },
              url:         { type: 'string', description: 'SharePoint or Documentum URL' },
              page:        { type: 'integer' },
              text:        { type: 'string' },
              score:       { type: 'number', description: 'Reranked relevance score' },
              bm25_score:  { type: 'number' },
              vector_score:{ type: 'number' },
            },
          },
        },
        total_retrieved: { type: 'integer' },
        query_latency_ms:{ type: 'integer' },
      },
    },
    runtime_config: {
      model: 'text-embedding-3-large',
      temperature: 0,
      max_tokens: 2048,
      top_p: 1,
      frequency_penalty: 0,
    },
    tools_used: ['Knowledge Engine API'],
    memory_settings: {
      type: 'none',
      window_size: 0,
      summarize_after: 0,
      store_embeddings: false,
    },
    timeout_seconds: 60,
    system_prompt: 'You are the Knowledge Retrieval Agent. You execute hybrid search queries against the WBG Azure AI Search index, apply cross-encoder reranking, enforce document-level access control, and return ranked chunks with inline source citations for downstream agents.',
    audit_log: [
      { event: 'created',  actor: 'admin@worldbank.org',       timestamp: '2025-01-15T09:00:00Z', delta: { version: '1.0.0', status: 'active', approval_status: 'Pending' } },
      { event: 'approved', actor: 'governance@worldbank.org',  timestamp: '2025-02-01T10:00:00Z', delta: { approval_status: 'Pending → Approved' } },
      { event: 'updated',  actor: 'km-unit@worldbank.org',     timestamp: '2025-04-10T14:00:00Z', delta: { version: '1.5.0', skills: '+Cross-encoder reranking' } },
    ],
  },
]
