export const AGENTS = [
  {
    id: 'agt-wb-001',
    name: 'Data Analyst Agent',
    version: '2.4.1',
    owner: 'Development Data Group (DDG)',
    description: 'Analyzes datasets, generates insights and visualizations from World Bank open data sources. Capable of multi-country comparisons, trend analysis, and automated report generation.',
    status: 'active',
    approval_status: 'Approved',
    data_classification: 'Official Use Only',
    allowed_user_roles: ['Economist', 'Data Scientist', 'Research Analyst', 'TTL'],
    skills: [
      'Time-series trend analysis',
      'Cross-country benchmarking',
      'Statistical regression modeling',
      'Automated chart generation',
      'WDI indicator querying',
      'Poverty & inequality metrics',
    ],
    supported_intents: [
      'analyze_gdp_trends',
      'compare_countries',
      'generate_report',
      'query_indicator',
      'calculate_poverty_headcount',
      'visualize_data',
    ],
    input_schema: {
      type: 'object',
      required: ['query'],
      properties: {
        query: { type: 'string', description: 'Natural language query about development data' },
        countries: { type: 'array', items: { type: 'string' }, description: 'ISO3 country codes' },
        indicators: { type: 'array', items: { type: 'string' }, description: 'WDI indicator codes' },
        date_range: {
          type: 'object',
          properties: {
            start: { type: 'string', format: 'date' },
            end: { type: 'string', format: 'date' },
          },
        },
      },
    },
    output_schema: {
      type: 'object',
      properties: {
        summary: { type: 'string' },
        data_points: { type: 'array' },
        charts: { type: 'array', items: { type: 'object', properties: { type: { type: 'string' }, url: { type: 'string' } } } },
        confidence_score: { type: 'number', minimum: 0, maximum: 1 },
        sources: { type: 'array', items: { type: 'string' } },
      },
    },
    runtime_config: {
      model: 'gpt-4o',
      temperature: 0.2,
      max_tokens: 4096,
      top_p: 0.95,
      frequency_penalty: 0.1,
    },
    tools_used: ['World Bank API', 'Data Visualizer', 'CSV Parser'],
    memory_settings: {
      type: 'sliding_window',
      window_size: 12,
      summarize_after: 20,
      store_embeddings: true,
    },
    timeout_seconds: 120,
    system_prompt: 'You are a data analysis expert specializing in World Bank development data. Your outputs must be accurate, cite sources, and follow World Bank data governance standards.',
    audit_log: [
      { event: 'created',   actor: 'admin@worldbank.org',         timestamp: '2024-03-01T09:00:00Z', delta: { version: '1.0.0', status: 'active', approval_status: 'Pending' } },
      { event: 'updated',   actor: 'ddg-lead@worldbank.org',      timestamp: '2024-06-15T14:22:00Z', delta: { version: '2.0.0', skills: '+Statistical regression modeling' } },
      { event: 'approved',  actor: 'governance@worldbank.org',    timestamp: '2024-07-01T11:10:00Z', delta: { approval_status: 'Pending → Approved' } },
      { event: 'updated',   actor: 'ddg-lead@worldbank.org',      timestamp: '2025-01-10T08:45:00Z', delta: { version: '2.4.1', runtime_config: 'model gpt-4 → gpt-4o' } },
    ],
  },
  {
    id: 'agt-wb-002',
    name: 'Policy Research Agent',
    version: '1.8.0',
    owner: 'Development Economics Vice Presidency (DEC)',
    description: 'Researches policy documents, synthesizes findings across World Bank reports and publications, and generates evidence-based policy briefs aligned with Bank operational standards.',
    status: 'active',
    approval_status: 'Approved',
    data_classification: 'Confidential',
    allowed_user_roles: ['Policy Analyst', 'Economist', 'TTL', 'Sector Specialist', 'VP'],
    skills: [
      'Policy document synthesis',
      'Multi-document summarization',
      'Evidence extraction',
      'Policy brief generation',
      'Regulatory framework analysis',
      'Cross-sectoral impact assessment',
    ],
    supported_intents: [
      'summarize_policy',
      'find_relevant_reports',
      'generate_policy_brief',
      'compare_policy_frameworks',
      'extract_recommendations',
      'assess_impact',
    ],
    input_schema: {
      type: 'object',
      required: ['query'],
      properties: {
        query: { type: 'string', description: 'Policy research question or topic' },
        sector: { type: 'string', enum: ['Education', 'Health', 'Infrastructure', 'Finance', 'Agriculture', 'Environment'] },
        region: { type: 'string', description: 'World Bank region code' },
        publication_years: { type: 'array', items: { type: 'integer' } },
        document_types: { type: 'array', items: { type: 'string', enum: ['Policy Note', 'Working Paper', 'Report', 'Brief'] } },
      },
    },
    output_schema: {
      type: 'object',
      properties: {
        brief: { type: 'string', description: 'Synthesized policy brief' },
        key_findings: { type: 'array', items: { type: 'string' } },
        recommendations: { type: 'array', items: { type: 'string' } },
        references: { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, url: { type: 'string' }, year: { type: 'integer' } } } },
        confidence_score: { type: 'number' },
      },
    },
    runtime_config: {
      model: 'gpt-4',
      temperature: 0.3,
      max_tokens: 8192,
      top_p: 0.9,
      frequency_penalty: 0.2,
    },
    tools_used: ['Web Search', 'PDF Reader', 'Text Summarizer'],
    memory_settings: {
      type: 'vector_store',
      window_size: 20,
      summarize_after: 30,
      store_embeddings: true,
    },
    timeout_seconds: 180,
    system_prompt: 'You are a policy research expert with deep knowledge of World Bank policy frameworks. Your outputs must be evidence-based, properly cited, and aligned with World Bank operational standards.',
    audit_log: [
      { event: 'created',   actor: 'admin@worldbank.org',         timestamp: '2024-05-12T10:00:00Z', delta: { version: '1.0.0', status: 'active', approval_status: 'Pending' } },
      { event: 'updated',   actor: 'dec-team@worldbank.org',      timestamp: '2024-08-20T13:05:00Z', delta: { version: '1.5.0', tools_used: '+Text Summarizer' } },
      { event: 'approved',  actor: 'governance@worldbank.org',    timestamp: '2024-09-03T09:30:00Z', delta: { approval_status: 'Pending → Approved' } },
      { event: 'updated',   actor: 'dec-team@worldbank.org',      timestamp: '2025-02-18T16:00:00Z', delta: { version: '1.8.0', memory_settings: 'type sliding_window → vector_store' } },
    ],
  },
]
