export const TOOLS = [
  {
    id: 'tool-ow-001',
    name: 'Knowledge Engine API',
    version: '3.1',
    category: 'RAG',
    status: 'active',
    system_affiliation: 'Azure AI Search',
    description: 'Hybrid semantic + BM25 keyword search over the WBG knowledge base (SharePoint Online, Documentum). Supports CPF documents, ESW reports, policy notes, ICRs, and global good practice literature. Applies cross-encoder reranking and enforces document-level access control.',
    maintainer: 'ITSOE / Knowledge Management Unit',
    input_schema: {
      type: 'object',
      required: ['query'],
      properties: {
        query:        { type: 'string', description: 'Natural language or structured search query' },
        country:      { type: 'string', description: 'Country filter (ISO3 or full name)' },
        doc_types:    { type: 'array', items: { type: 'string', enum: ['CPF', 'Policy Note', 'ESW', 'ICR', 'Working Paper', 'Report', 'Template'] } },
        top_k:        { type: 'integer', default: 10, minimum: 1, maximum: 50 },
        rerank:       { type: 'boolean', default: true, description: 'Apply cross-encoder reranking before returning results' },
        access_level: { type: 'string', enum: ['public', 'official', 'confidential'] },
      },
    },
    output_schema: {
      type: 'object',
      properties: {
        chunks: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              chunk_id:     { type: 'string' },
              document:     { type: 'string' },
              url:          { type: 'string', description: 'SharePoint or Documentum source URL' },
              page:         { type: 'integer' },
              text:         { type: 'string' },
              score:        { type: 'number', description: 'Final reranked score (0–1)' },
              bm25_score:   { type: 'number' },
              vector_score: { type: 'number' },
            },
          },
        },
        total_retrieved:  { type: 'integer' },
        query_latency_ms: { type: 'integer' },
      },
    },
    authentication: {
      type: 'bearer',
      notes: 'Requires World Bank Entra ID managed identity bearer token. Enforces document-level ACL — agents receive only documents the invoking user is authorized to access.',
      header: 'Authorization: Bearer <entra-token>',
      token_env_var: 'WB_KNOWLEDGE_ENGINE_TOKEN',
    },
    rate_limits: {
      requests_per_minute: 30,
      daily_quota: 5000,
      burst_limit: 10,
      retry_after_header: 'Retry-After',
      throttle_policy: 'Sliding window per agent ID',
    },
    usage_policies: [
      'All queries are logged with agent ID, query text, and retrieved chunk IDs for audit purposes.',
      'Retrieved content must not be cached for longer than 1 hour.',
      'Document-level ACL is enforced server-side — agents must not attempt to bypass access controls.',
      'Reranking scores and retrieved chunk references must be surfaced in the observability dashboard.',
      'Agents must cite source documents inline in all generated outputs.',
    ],
    tags: ['RAG', 'Knowledge', 'Azure AI Search', 'SharePoint', 'Documentum'],
  },
  {
    id: 'tool-ow-002',
    name: 'Dataverse Connector',
    version: '2.4',
    category: 'Enterprise',
    status: 'active',
    system_affiliation: 'Dataverse',
    description: 'MCP-compliant connector to the OW Dataverse instance. Supports read and write operations on ASA records, project entities, CPF mappings, and portfolio data. All write operations are validated against the ASA entity schema before commit. Returns record IDs for downstream reference.',
    maintainer: 'OW Platform Engineering Team',
    input_schema: {
      type: 'object',
      required: ['operation', 'entity'],
      properties: {
        operation:   { type: 'string', enum: ['read', 'create', 'update', 'query'], description: 'CRUD operation type' },
        entity:      { type: 'string', enum: ['asa_record', 'project', 'cpf_mapping', 'portfolio_item'], description: 'Dataverse entity name' },
        record_id:   { type: 'string', description: 'Record GUID for read/update operations' },
        filters:     { type: 'object', description: 'OData filter expressions for query operations' },
        payload:     { type: 'object', description: 'Field values for create/update operations' },
        validate_schema: { type: 'boolean', default: true, description: 'Validate payload against entity schema before write' },
      },
    },
    output_schema: {
      type: 'object',
      properties: {
        record_id:    { type: 'string', description: 'GUID of created or updated record' },
        records:      { type: 'array', description: 'Array of matching records for query operations' },
        status:       { type: 'string', enum: ['success', 'validation_error', 'permission_denied', 'not_found'] },
        errors:       { type: 'array', items: { type: 'string' }, description: 'Schema validation or permission errors' },
        etag:         { type: 'string', description: 'OData ETag for optimistic concurrency' },
      },
    },
    authentication: {
      type: 'oauth2',
      notes: 'Entra ID OAuth2 service principal authentication. The agent must have been granted explicit write permissions to the ASA entity in the Agent Registry tool grants. Unauthorized write attempts are blocked and logged.',
      header: 'Authorization: Bearer <oauth2-token>',
      token_env_var: 'WB_DATAVERSE_TOKEN',
    },
    rate_limits: {
      requests_per_minute: 60,
      daily_quota: 10000,
      burst_limit: 20,
      retry_after_header: 'Retry-After',
      throttle_policy: 'Fixed window per agent ID with circuit breaker',
    },
    usage_policies: [
      'All write operations require explicit tool grant declared in the Agent Registry.',
      'Payload must be validated against the ASA entity schema before any write is committed.',
      'All invocations are logged with agent ID, operation type, entity, sanitized inputs, response status, and latency.',
      'PII fields in retrieved records must be redacted before passing to downstream agents.',
      'Circuit breaker activates after 5 consecutive failures — retry only after 60-second cooldown.',
    ],
    tags: ['Dataverse', 'OW', 'ASA', 'Enterprise', 'Write'],
  },
  {
    id: 'tool-ow-003',
    name: 'SharePoint Connector',
    version: '1.8',
    category: 'Enterprise',
    status: 'active',
    system_affiliation: 'SharePoint',
    description: 'MCP-compliant connector to SharePoint Online for document upload, template retrieval, and metadata tagging. Supports MTI, FCI, HNP, and other Global Practice document libraries. Returns SharePoint document URLs for Dataverse record linkage.',
    maintainer: 'OW Platform Engineering Team',
    input_schema: {
      type: 'object',
      required: ['operation'],
      properties: {
        operation:    { type: 'string', enum: ['upload', 'retrieve', 'search', 'tag'], description: 'SharePoint operation type' },
        site_url:     { type: 'string', description: 'SharePoint site URL or Global Practice site identifier' },
        library:      { type: 'string', description: 'Document library name (e.g. "ASA Concept Notes", "Templates")' },
        file_name:    { type: 'string', description: 'Document filename for upload/retrieve' },
        content:      { type: 'string', description: 'Base64-encoded document content for upload' },
        metadata:     {
          type: 'object',
          description: 'SharePoint metadata tags',
          properties: {
            asa_record_id: { type: 'string' },
            country:       { type: 'string' },
            global_practice: { type: 'string' },
            document_type: { type: 'string' },
            asa_type:      { type: 'string' },
            topic_codes:   { type: 'array', items: { type: 'string' } },
            status:        { type: 'string', enum: ['Draft', 'Submitted', 'Approved'] },
          },
        },
        search_query: { type: 'string', description: 'Full-text search query for document retrieval' },
      },
    },
    output_schema: {
      type: 'object',
      properties: {
        document_url:   { type: 'string', description: 'SharePoint URL of uploaded or retrieved document' },
        documents:      { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, url: { type: 'string' }, modified: { type: 'string' } } } },
        status:         { type: 'string', enum: ['success', 'permission_denied', 'not_found', 'quota_exceeded'] },
        metadata_applied: { type: 'object', description: 'Confirmed metadata tags applied to the document' },
      },
    },
    authentication: {
      type: 'oauth2',
      notes: 'Entra ID OAuth2 with SharePoint app-only permissions scoped to OW document libraries. Write operations require explicit tool grant from Agent Registry.',
      header: 'Authorization: Bearer <oauth2-token>',
      token_env_var: 'WB_SHAREPOINT_TOKEN',
    },
    rate_limits: {
      requests_per_minute: 30,
      file_size_mb: 100,
      daily_quota: 2000,
      retry_after_header: 'Retry-After',
      throttle_policy: 'Sliding window per agent ID',
    },
    usage_policies: [
      'Documents may only be uploaded to approved OW Global Practice libraries.',
      'All upload operations must include mandatory metadata: ASA record ID, country, GP, document type, and status.',
      'SharePoint document URL must be written back to the linked Dataverse ASA record after upload.',
      'Retrieval operations are logged for audit — document title, URL, and accessing agent ID are recorded.',
      'Confidential documents require explicit TTL approval before access.',
    ],
    tags: ['SharePoint', 'OW', 'Document', 'Enterprise', 'Upload'],
  },
  {
    id: 'tool-ow-004',
    name: 'Azure SQL Connector',
    version: '1.2',
    category: 'Data',
    status: 'active',
    system_affiliation: 'Azure AI Search',
    description: 'Read-only connector to the OW Azure SQL database for financial summary data — committed budgets, disbursements, disbursement rates, and closing dates for active and pipeline ASAs. Used primarily for portfolio overlap enrichment and financial context retrieval.',
    maintainer: 'OW Data Engineering Team',
    input_schema: {
      type: 'object',
      required: ['query_type'],
      properties: {
        query_type:    { type: 'string', enum: ['financial_summary', 'asa_list', 'disbursement_detail', 'pipeline_overview'], description: 'Parameterized query template to execute' },
        country:       { type: 'string', description: 'Filter by country ISO3 or name' },
        global_practice: { type: 'string', description: 'Filter by GP code' },
        topic_codes:   { type: 'array', items: { type: 'string' } },
        status_filter: { type: 'array', items: { type: 'string', enum: ['Active', 'Pipeline', 'Closed'] } },
        fiscal_year:   { type: 'integer', description: 'WBG fiscal year (e.g. 2025)' },
        limit:         { type: 'integer', default: 50, maximum: 200 },
      },
    },
    output_schema: {
      type: 'object',
      properties: {
        records:     { type: 'array', description: 'Array of ASA financial records' },
        summary:     { type: 'object', properties: { total_committed_usd: { type: 'number' }, total_disbursed_usd: { type: 'number' }, disbursement_rate_pct: { type: 'number' }, count: { type: 'integer' } } },
        query_ms:    { type: 'integer', description: 'Query execution time in milliseconds' },
      },
    },
    authentication: {
      type: 'bearer',
      notes: 'Entra ID managed identity token. Read-only access — no write operations permitted. Results are scoped to entities the calling agent has been granted access to.',
      header: 'Authorization: Bearer <entra-token>',
      token_env_var: 'WB_AZURE_SQL_TOKEN',
    },
    rate_limits: {
      requests_per_minute: 20,
      daily_quota: 3000,
      burst_limit: 5,
      retry_after_header: 'Retry-After',
      throttle_policy: 'Fixed window per agent ID',
    },
    usage_policies: [
      'Read-only access only — no INSERT, UPDATE, or DELETE operations are permitted.',
      'Query results are scoped to entities the calling agent has been explicitly granted access to.',
      'Financial data must not be cached for longer than 4 hours.',
      'All queries are logged with agent ID, query type, parameters, and row count returned.',
      'Aggregated financial outputs must be attributed to the OW financial data system in all reports.',
    ],
    tags: ['Azure SQL', 'Finance', 'Portfolio', 'Read-Only'],
  },
  {
    id: 'tool-ow-005',
    name: 'SAP Connector',
    version: '1.0',
    category: 'Enterprise',
    status: 'active',
    system_affiliation: 'SAP',
    description: 'MCP-compliant connector to the World Bank SAP Financial Management System (FMS). Registered and available in the Tool Registry for future PoC phases. Not exercised in the current ASA Creation PoC but must be discoverable by agents.',
    maintainer: 'ITS Financial Systems Team',
    input_schema: {
      type: 'object',
      required: ['operation'],
      properties: {
        operation:    { type: 'string', enum: ['read_budget', 'read_commitment', 'read_disbursement'], description: 'SAP FMS query operation' },
        cost_center:  { type: 'string', description: 'SAP cost center code' },
        wbs_element:  { type: 'string', description: 'SAP WBS element identifier' },
        fiscal_year:  { type: 'integer', description: 'SAP fiscal year' },
      },
    },
    output_schema: {
      type: 'object',
      properties: {
        budget_amount:      { type: 'number' },
        committed_amount:   { type: 'number' },
        disbursed_amount:   { type: 'number' },
        available_balance:  { type: 'number' },
        currency:           { type: 'string', default: 'USD' },
        as_of_date:         { type: 'string', format: 'date' },
      },
    },
    authentication: {
      type: 'oauth2',
      notes: 'SAP OAuth2 via WBG Entra ID federation. Requires FMS read role assignment. Not active in current PoC scope.',
      header: 'Authorization: Bearer <sap-oauth-token>',
      token_env_var: 'WB_SAP_FMS_TOKEN',
    },
    rate_limits: {
      requests_per_minute: 10,
      daily_quota: 1000,
      burst_limit: 3,
      retry_after_header: 'Retry-After',
      throttle_policy: 'Fixed window per agent ID',
    },
    usage_policies: [
      'SAP FMS data is strictly confidential — access restricted to authorized financial officers and TTLs.',
      'No financial data may be exported outside of approved WBG reporting systems.',
      'This connector is registered for discoverability but is not exercised in the current PoC run.',
      'All access attempts are logged and reviewed by the ITS Financial Systems audit team.',
    ],
    tags: ['SAP', 'FMS', 'Finance', 'Enterprise', 'Registered'],
  },
]
