export const TOOLS = [
  {
    id: 'tool-wb-001',
    name: 'World Bank API',
    version: '2.0',
    category: 'Data',
    status: 'active',
    description: 'Access World Bank Open Data API for development indicators, country statistics, and project data across 217 economies.',
    maintainer: 'Development Data Group (DDG)',
    input_schema: {
      type: 'object',
      required: ['indicator'],
      properties: {
        indicator: { type: 'string', description: 'WDI indicator code (e.g. NY.GDP.MKTP.CD)', example: 'NY.GDP.MKTP.CD' },
        country: { type: 'string', description: 'ISO3 country code or "all"', example: 'ZAF' },
        date_range: { type: 'string', description: 'Year range (e.g. 2010:2023)', example: '2010:2023' },
        format: { type: 'string', enum: ['json', 'xml', 'csv'], default: 'json' },
        per_page: { type: 'integer', minimum: 1, maximum: 1000, default: 50 },
        mrv: { type: 'integer', description: 'Most recent N values', minimum: 1, maximum: 10 },
      },
    },
    output_schema: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          indicator: { type: 'object', properties: { id: { type: 'string' }, value: { type: 'string' } } },
          country: { type: 'object', properties: { id: { type: 'string' }, value: { type: 'string' } } },
          countryiso3code: { type: 'string' },
          date: { type: 'string' },
          value: { type: 'number' },
          unit: { type: 'string' },
          obs_status: { type: 'string', enum: ['', 'E', 'M', 'N', 'P'] },
          decimal: { type: 'integer' },
        },
      },
    },
    authentication: {
      type: 'none',
      notes: 'Public API — no authentication required. Requests from the same IP are pooled for rate limiting.',
      header: null,
      token_env_var: null,
    },
    rate_limits: {
      requests_per_minute: 100,
      daily_quota: 50000,
      burst_limit: 20,
      retry_after_header: 'Retry-After',
      throttle_policy: 'Fixed window per IP address',
    },
    usage_policies: [
      'Data must be attributed to the World Bank Open Data platform.',
      'Bulk downloads must use the bulk download facility, not the API.',
      'API must not be used to build derivative datasets for commercial redistribution without permission.',
      'Results must not be cached for longer than 24 hours without re-validation.',
      'Any application using this API must comply with the World Bank Terms of Use.',
    ],
    tags: ['Data', 'Economics', 'Official'],
  },
  {
    id: 'tool-wb-002',
    name: 'PDF Reader',
    version: '1.3',
    category: 'Document',
    status: 'active',
    description: 'Extract, parse, and semantically chunk text from PDF documents including World Bank reports, policy briefs, and working papers. Supports OCR for scanned documents.',
    maintainer: 'ITS Infrastructure Team',
    input_schema: {
      type: 'object',
      required: ['source'],
      properties: {
        source: { type: 'string', description: 'Publicly accessible URL or base64-encoded PDF' },
        pages: { type: 'string', description: 'Page range (e.g. "1-10" or "all")', default: 'all' },
        extract_tables: { type: 'boolean', default: false, description: 'Return tables as structured JSON arrays' },
        extract_figures: { type: 'boolean', default: false, description: 'Return figure captions and alt text' },
        chunk_size: { type: 'integer', default: 1000, description: 'Token size per semantic chunk' },
        language: { type: 'string', default: 'en', enum: ['en', 'fr', 'es', 'ar', 'zh'], description: 'Document language hint for OCR' },
      },
    },
    output_schema: {
      type: 'object',
      properties: {
        text: { type: 'string', description: 'Full concatenated extracted text' },
        chunks: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              page: { type: 'integer' },
              text: { type: 'string' },
              tokens: { type: 'integer' },
              embedding_id: { type: 'string', description: 'Vector store reference ID if embeddings enabled' },
            },
          },
        },
        tables: { type: 'array', description: 'Extracted tables as arrays of row objects' },
        metadata: {
          type: 'object',
          properties: {
            title: { type: 'string' },
            author: { type: 'string' },
            created_date: { type: 'string', format: 'date' },
            page_count: { type: 'integer' },
            word_count: { type: 'integer' },
            language_detected: { type: 'string' },
          },
        },
      },
    },
    authentication: {
      type: 'bearer',
      notes: 'Internal service — requires a valid World Bank SSO-issued bearer token. Token lifetime is 1 hour.',
      header: 'Authorization: Bearer <token>',
      token_env_var: 'WB_PDF_READER_TOKEN',
    },
    rate_limits: {
      requests_per_minute: 20,
      file_size_mb: 50,
      max_pages_per_request: 500,
      concurrent_requests: 3,
      throttle_policy: 'Sliding window per authenticated user',
    },
    usage_policies: [
      'Only documents hosted on official World Bank or partner domains may be processed.',
      'Extracted content must not be stored outside approved World Bank data repositories.',
      'PII identified in documents must be redacted before passing to downstream agents.',
      'Use of this tool on confidential documents (classification: CONF or higher) requires explicit TTL approval.',
      'Processing logs are retained for 90 days for audit purposes.',
    ],
    tags: ['Document', 'NLP', 'Internal'],
  },
]
